### ISSUE TITLE
panic on ttl command

### ISSUE THREAD

**Issue by mkorolyov** [SuperStas/yams#1]
```
panic: runtime error: index out of range

goroutine 1610 [running]:
storage.(*KeyRegistry).InvokeOperation(0xc820010c40, 0xc8204794b0, 0x3, 0xc8204794b4, 0x1, 0xc820458860, 0x0, 0x0, 0x0, 0x0, ...)
        /home/akolesen/work/juno/tmp/yams/src/storage/key_registry.go:92 +0x82d
server.(*Server).handleRequest(0xc820022690, 0x7f73e1ba3000, 0xc82003e058)
        /home/akolesen/work/juno/tmp/yams/src/server/server.go:84 +0x5e9
created by server.(*Server).Start
        /home/akolesen/work/juno/tmp/yams/src/server/server.go:59 +0x48b
```

`echo "ttl 1 \n" | nc localhost 54321;`

**Comment by SuperStas** [comment]
@mkorolyov, thanks for report. Fixed.
