### ISSUE TITLE
Panic on lupdate command list_type:40

### ISSUE THREAD

**Issue by mkorolyov** [SuperStas/yams#2]
```
panic: runtime error: index out of range

goroutine 18 [running]:
storage.(*ListDataType).Invoke(0xc82003e080, 0xc8200a6060, 0x7, 0xc8200a6068, 0x1, 0xc8200aa140, 0x0, 0x0, 0xc820010c40, 0x0, ...)
        /home/akolesen/work/juno/tmp/yams/src/storage/list_type.go:40 +0x8ce
storage.(*KeyRegistry).InvokeOperation(0xc820010c40, 0xc8200a6060, 0x7, 0xc8200a6068, 0x1, 0xc8200aa140, 0x0, 0x0, 0x0, 0x0, ...)
        /home/akolesen/work/juno/tmp/yams/src/storage/key_registry.go:104 +0x942
server.(*Server).handleRequest(0xc820022690, 0x7f1a1c59b000, 0xc8200b8000)
        /home/akolesen/work/juno/tmp/yams/src/server/server.go:84 +0x5e9
created by server.(*Server).Start
        /home/akolesen/work/juno/tmp/yams/src/server/server.go:59 +0x48b
```
`echo "lupdate 1" | nc localhost 54321;`

**Comment by SuperStas** [comment]
@mkorolyov, thanks for report. Fixed.
