### ISSUE TITLE
Panic on ldel command

### ISSUE THREAD

**Issue by mkorolyov** [SuperStas/yams#3]
```
goroutine 18 [running]:
storage.(*ListDataType).Invoke(0xc82003e080, 0xc8200a4050, 0x4, 0xc8200a4055, 0x1, 0xc8200a8120, 0x0, 0x0, 0xc820010c40, 0x0, ...)
        /home/akolesen/work/juno/tmp/yams/src/storage/list_type.go:46 +0x386
storage.(*KeyRegistry).InvokeOperation(0xc820010c40, 0xc8200a4050, 0x4, 0xc8200a4055, 0x1, 0xc8200a8120, 0x0, 0x0, 0x0, 0x0, ...)
        /home/akolesen/work/juno/tmp/yams/src/storage/key_registry.go:104 +0x942
server.(*Server).handleRequest(0xc820022690, 0x7f7988203000, 0xc8200ae000)
        /home/akolesen/work/juno/tmp/yams/src/server/server.go:84 +0x5e9
created by server.(*Server).Start
        /home/akolesen/work/juno/tmp/yams/src/server/server.go:59 +0x48b

```
`echo "ldel 1" | nc localhost 54321;`

**Comment by SuperStas** [comment]
@mkorolyov, thanks for report. Fixed.
