### ISSUE TITLE
Panic on hupdate command

### ISSUE THREAD

**Issue by mkorolyov** [SuperStas/yams#4]
```
panic: runtime error: index out of range

goroutine 18 [running]:
storage.(*HashDataType).Invoke(0xc82003e078, 0xc8200a6040, 0x7, 0xc8200a6048, 0x1, 0xc8200aa100, 0x0, 0x0, 0xc820010c40, 0x0, ...)
        /home/akolesen/work/juno/tmp/yams/src/storage/hash_type.go:47 +0x59f
storage.(*KeyRegistry).InvokeOperation(0xc820010c40, 0xc8200a6040, 0x7, 0xc8200a6048, 0x1, 0xc8200aa100, 0x0, 0x0, 0x0, 0x0, ...)
        /home/akolesen/work/juno/tmp/yams/src/storage/key_registry.go:104 +0x942
server.(*Server).handleRequest(0xc820022690, 0x7f5022db2000, 0xc8200b2000)
        /home/akolesen/work/juno/tmp/yams/src/server/server.go:84 +0x5e9
created by server.(*Server).Start
        /home/akolesen/work/juno/tmp/yams/src/server/server.go:59 +0x48b
```

`echo "hupdate 1" | nc localhost 54321;`

**Comment by SuperStas** [comment]
@mkorolyov thanks for report. Fixed.
