### ISSUE TITLE
panic on hdel command

### ISSUE THREAD

**Issue by mkorolyov** [SuperStas/yams#5]
```
panic: runtime error: index out of range

goroutine 9 [running]:
storage.(*HashDataType).Invoke(0xc82003e078, 0xc82000b160, 0x4, 0xc82000b165, 0x1, 0xc820011140, 0x0, 0x0, 0xc820010c40, 0x0, ...)
        /home/akolesen/work/juno/tmp/yams/src/storage/hash_type.go:49 +0x1f1
storage.(*KeyRegistry).InvokeOperation(0xc820010c40, 0xc82000b160, 0x4, 0xc82000b165, 0x1, 0xc820011140, 0x0, 0x0, 0x0, 0x0, ...)
        /home/akolesen/work/juno/tmp/yams/src/storage/key_registry.go:104 +0x942
server.(*Server).handleRequest(0xc820022690, 0x7f36d4c5d740, 0xc82003e0b8)
        /home/akolesen/work/juno/tmp/yams/src/server/server.go:84 +0x5e9
created by server.(*Server).Start
        /home/akolesen/work/juno/tmp/yams/src/server/server.go:59 +0x48b
```

`echo "hdel 1" | nc localhost 54321;`

**Comment by SuperStas** [comment]
@mkorolyov, thanks for report. Fixed.
