### ISSUE TITLE
panic on lupdate command list_type:44

### ISSUE THREAD

**Issue by mkorolyov** [SuperStas/yams#8]
```
goroutine 8 [running]:
storage.(*ListDataType).Invoke(0xc82003e080, 0xc82000b760, 0x7, 0xc82000b768, 0x2, 0xc820019970, 0x1, 0x1, 0xc820010c40, 0x0, ...)
        /home/akolesen/work/juno/tmp/yams/src/storage/list_type.go:44 +0x8c7
storage.(*KeyRegistry).InvokeOperation(0xc820010c40, 0xc82000b760, 0x7, 0xc82000b768, 0x2, 0xc820019970, 0x1, 0x1, 0x0, 0x0, ...)
        /home/akolesen/work/juno/tmp/yams/src/storage/key_registry.go:104 +0x942
server.(*Server).handleRequest(0xc820022690, 0x7f5494092740, 0xc82003e0b0)
        /home/akolesen/work/juno/tmp/yams/src/server/server.go:84 +0x5e9
created by server.(*Server).Start
        /home/akolesen/work/juno/tmp/yams/src/server/server.go:59 +0x48b

```

`echo "lupdate -1 666" | nc localhost 54321;`

**Comment by SuperStas** [comment]
@mkorolyov, thanks for report. Fixed.
